/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tuandhpc05076.Form;

import com.tuandhpc05076.swing0.Form;
import java.awt.Color;
import test.Slide1;
import test.Slide2;
import test.Slide3;

/**
 *
 * @author DELL E5470
 */
public class Home_Form extends Form {

    /**
     * Creates new form Home
     */
    public Home_Form() {
        initComponents();
        
        slideshow1.initSlideshow(new Slide1(), new Slide2(), new Slide3());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slideshow1 = new slideshow.Slideshow();
        jPanel2 = new javax.swing.JPanel();
        card9 = new com.tuandhpc05076.swing0.Card();
        card10 = new com.tuandhpc05076.swing0.Card();
        card4 = new com.tuandhpc05076.swing0.Card();
        card8 = new com.tuandhpc05076.swing0.Card();

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        card9.setColor1(new java.awt.Color(51, 255, 51));
        card9.setColor2(new java.awt.Color(255, 255, 204));
        jPanel2.add(card9);

        card10.setColor1(new java.awt.Color(51, 255, 51));
        card10.setColor2(new java.awt.Color(255, 255, 204));
        jPanel2.add(card10);

        card4.setColor1(new java.awt.Color(51, 255, 51));
        card4.setColor2(new java.awt.Color(255, 255, 204));
        jPanel2.add(card4);

        card8.setColor1(new java.awt.Color(51, 255, 51));
        card8.setColor2(new java.awt.Color(255, 255, 204));
        jPanel2.add(card8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slideshow1, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(slideshow1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(386, 386, 386))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tuandhpc05076.swing0.Card card10;
    private com.tuandhpc05076.swing0.Card card4;
    private com.tuandhpc05076.swing0.Card card8;
    private com.tuandhpc05076.swing0.Card card9;
    private javax.swing.JPanel jPanel2;
    private slideshow.Slideshow slideshow1;
    // End of variables declaration//GEN-END:variables
}
